name: open5gs
kind: cnf
provider: Open5GS
productName: Open5GS
version: "2.7.5"
releaseDate: 2025-05-19T23:20:50.52Z
manifests:  
  - name: open5gs    
    sourceRepo: tcp-gitops
    sourceRepoRevision: HEAD   
    path: charts/open5gs   
    valuesRepo: tcp-gitops  
    valuesRepoRevision: HEAD    
    valuesFiles:      
        - config/values.yaml
namespace: open5gs
dip:  
    name: open5gs-dip  
    version: 1
